.IX Title "devede 1"
.TH devede 1 "2009-08-25" "" ""
.\" For nroff, turn off justification.  Always turn off hyphenation; it makes
.\" way too many mistakes in technical documents.
.if n .ad l
.nh
.SH "NAME"
\&\fBdevede\fR \- A simple application to create Video DVDs
.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
.B devede
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
\&\fBDeVeDe\fR allows users to create Video DVDs, suitable for home players, \
from any number of video files, in any of the formats supported by Mplayer.
.PP
It also allows user to create subtitles and even animated menus.
.PP
\&\fBDeVeDe\fR has been written in Python and GTK+ and after the \
installation the application is available from the Applications menu.
.SH "AUTHOR"
.IX Header "AUTHOR"
\fBDeVeDe\fR was written by Sergio Costas <raster@rastersoft.com>
.PP
This manual was provided by Alessio Treglia <quadrispro@ubuntu.com> \
for the Ubuntu project (and may be used by others).
